### ISSUE TITLE
CORS problem

### ISSUE THREAD

**Issue by Naticus** [moussetc/mattermost-plugin-spoiler#14]
I'm having an issue that I haven't been able to figure out when I enable this plugin.  I'm not sure if something is breaking entirely, but in Firefox I'm seeing this error for the plugin:

`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://plugins/com.github.moussetc.mattermost.plugin.spoiler/config. (Reason: CORS request did not succeed).`

Now obviously it shouldn't be pointing to "https://plugins" but rather "https://domain.com/plugins" but I can't find anywhere to change this behavior.  Any advice?

**Comment by moussetc** [comment]
If your Mattermost server version allows it, please try the latest 3.0.0 version.

Is the Mattermost Setting Site URL configured in the admin console?

If not, or if the problem is not resolved, please provide the following information:
- Mattermost server version
- plugin version
- are you using the highlight ("redacted") mode or the button mode?
- is the error shown when you use the spoiler command or when you activate the plugin? If it is the second, does the command work anyway?

**Comment by Naticus** [comment]
Seems to be working just fine now!  I'm on server 5.21 and have used both the highlight and button mode, but because so many of my users use on mobile I've opted to use the button instead.  I'll go ahead and mark this as closed.

**Comment by Naticus** [comment]
Oh, I see that if I'm in highlight mode that it still uses the button on mobile now.  That's like the best of both worlds, perfect!  Thanks @moussetc
