### ISSUE TITLE
Add to Marketplace

### ISSUE THREAD

**Issue by OverdueWeevil2** [moussetc/mattermost-plugin-spoiler#22]

**Comment by floviolleau** [comment]
Hi,

Could you please add it to marketplace?

Thanks

**Comment by moussetc** [comment]
Hi,

I have one plugin already in the marketplace, and the [PR to update it](https://github.com/mattermost/mattermost-marketplace/issues/236) has been waiting for *more than a year* to be integrated in the MM marketplace ; I'm afraid this spoiler plugin is not going to be integrated to the Marketplace any time soon.

You can still use the GitHub releases download for the spoiler plugin (see README for installation instructions). You can also vote on the [uservoice issue to add support to Mattermost](https://mattermost.uservoice.com/forums/306457-general/suggestions/13381623-add-a-way-to-spoiler-some-messages-or-part-of-mess).

**Comment by moussetc** [comment]
Last year, it was announced that Mattermost was going to remove community plugins from the in-product Marketplace (see https://github.com/mattermost/mattermost-marketplace/issues/365#issuecomment-1638893037). 

The spoiler plugin is already displayed in the [web marketplace](https://mattermost.com/marketplace/spoiler-plugin/), though you'll need to install the plugin manually as per my previous comment, for lack of a better option.

Though really, do please take the 2min required to go vote on the [uservoice issue to add support to Mattermost](https://mattermost.uservoice.com/forums/306457-general/suggestions/13381623-add-a-way-to-spoiler-some-messages-or-part-of-mess) because an official implementation would be so much better that what can be achieved through a plugin ;)

As such, I will be closing this issue.
