### ISSUE TITLE
400 bad request when clicking on "Show spoiler"

### ISSUE THREAD

**Issue by jake-tulip** [moussetc/mattermost-plugin-spoiler#4]
Hey moussetc!

We're having a bug when we've installed the latest build.

When clicking the spoiler button an HTTP POST is made:

`https://mattermost.<our website>/api/v4/posts/<post_id>/actions/<action_id>`

The response is a 400 Bad Request:

`{"id":"api.post.do_action.action_integration.app_error","message":"Action integration error","detailed_error":"","request_id":"<request id>","status_code":400}`

Do we maybe not have specific features enabled for the api? Or our installation was incorrect?

**Comment by moussetc** [comment]
Hi! I won't be able to look into it right now, but could you already tell me the exact version of Mattermost server you're using, and whether you already had the plugin working on a previous version install? Also, are you behind a proxy?

**Comment by jake-tulip** [comment]
```
Mattermost Version: 5.6.1
Database Schema Version: 5.6.0
Database: mysql
```

**Comment by moussetc** [comment]
I couldn't reproduce the bug on a clean Mattermost 5.6.1 install, using Docker.

- What is your Mattermost installation setup (OS, using Docker or not, etc.) ?
- Set temporarily the log level to Debug (System Console>Logging>Console Log Level), and try the spoiler button again: do you have any log that appears in System Console>Logs? 
- Do you have other plugins installed that actually manage to communicate with the server?

**Comment by clarfon** [comment]
We have the same issue. In the logs, we're getting:

```
{"level":"error","ts":1555908064.5662103,"caller":"web/context.go:52","msg":"Action integration error","path":"/api/v4/posts/.../actions/7yogo7dbbi8i7p137suyrnjqae","request_id":"3yzqkzn1zjdg8meqcu1ub971ro","ip_addr":"...","user_id":"...","method":"POST","err_where":"DoActionRequest","http_code":400,"err_details":"err=Post .../plugins/com.github.moussetc.mattermost.plugin.spoiler/show: http: server gave HTTP response to HTTPS client"}
```

(`...` placed to redact stuff)

**Comment by hanzei** [comment]
Did you made sure to set your `SiteURL` to `https`?

**Comment by jake-tulip** [comment]
@hanzei in what regard do I need to set the `SiteURL`? Just using the latest build.

**Comment by hanzei** [comment]
You need to set a `SiteURL` in the system console. See https://docs.mattermost.com/administration/config-settings.html#site-url

**Comment by moussetc** [comment]
@jake-tulip If setting the `SiteURL` does not work, please provide us with the log line from System Console>Logs so we can see the error details.
If you can give us some details about your Mattermost installation setup (OS, using Docker or not, HTTPS activated, etc.), that's be helpful.

@hanzei thanks for your help, it's much appreciated!

**Comment by clarfon** [comment]
Sorry for the delay: we're reverse-proxied through Apache which terminates SSL and forwards to mattermost via HTTP. We're running 5.9 though and I was planning to update to 5.10 within a few days, so, I'll let you know if that fixes it. We have the same problem with matterpoll, as I recently found out, and it may just be a mattermost bug.

**Comment by clarfon** [comment]
Took a while getting around to updating, but the update didn't fix it.

**Comment by clarfon** [comment]
…and, I found out that this was an Apache error on our end. Wow, that was tough to debug.

Anyway, this is unrelated to this plugin so you're all good, at least on our end. :+1:

**Comment by 143mailliw** [comment]
@clarfon Just a note, but it seems like NGINX seems to work better with Mattermost.

**Comment by walterl** [comment]
Hi there!

I'm experiencing the same issue as @clarfon, albeit with a slightly different error in the logs:

```json
"err_details":"err=Post https://mysite.redacted/plugins/com.github.moussetc.mattermost.plugin.spoiler/show: x509: certificate signed by unknown authority"
```

My `SiteURL` is correct for my setup. I'm reverse proxying (nginx, where HTTPS terminates) to a Docker container where Mattermost is running. The SSL certificate configured on the proxy is issued by my own CA, so the error makes sense. However, this plugin probably shouldn't have to deal with such details.

This is the first enabled plugin, and the rest of the server has been running without a hitch for a few months now.

Mattermost Version: 5.7.1
Database Schema Version: 5.7.0

**Comment by clarfon** [comment]
@walterl you most likely don't include the full cert chain in the response. Try curling the server instead of opening in a browser.

**Comment by walterl** [comment]
Clients connecting to my server have the CA cert installed, and have no connection/cert issues. Therefore I suspect that the error is caused by the CA cert not being installed in the Mattermost Docker container, which is why it thinks that the CA is "unknown".

Regardless, isn't such CA verification out of scope for this plugin? Especially when everything else (including the main Mattermost server) works perfectly.

**Comment by moussetc** [comment]
@walterl I think you are right about the CA not being installed in the docker being a cause for https error.

However if the reverse proxy is configured to transform all https request to http, it shouldn't matter. Have you looked at the nginx/mattermost logs to check that the request made when the spoiler button is clicked does arrive correctly as http to the mattermost server?

The plugin does not do any HTTP stuff on it's own: it relies on the mattermost server plugin (`serveHttp()`) so I don't think it's trivial - nor a good idea - to disable this security check.

**Comment by walterl** [comment]
Hi @moussetc 

> Have you looked at the nginx/mattermost logs to check that the request made when the spoiler button is clicked does arrive correctly as http to the mattermost server?

The fact Mattermost has no connection security configured (_Connection Security: None_), and the rest of the server works fine, indicates to me that the requests do indeed arrive as HTTP. But you raise an interesting question: If the nginx reverse proxy is configured to proxy HTTP only (`proxy_pass http://mattermost_docker;`), what HTTPS traffic is it failing to verify? I.e. my custom CA should not have any influence, since it's all HTTP from the Mattermost server's point of view.

The only mention of HTTPS in my configuration is in my _Site URL_, which starts with `https://`. Could it be that this is a bug in the Mattermost code, where its plugin system tries to verify a plugin request's connection as HTTPS, based solely on the site URL?

FYI, the browser in which I'm running Mattermost receives the same "Action integration error" HTTP 400 response as OP.

I'll dig into the code a bit, ASAP.

**Comment by moussetc** [comment]
Hmm I think it goes like this:
1. The plugin writes the integration URL for the button, using the SiteURL setting. In this case, the integration request is HTTPS.
2. On the button click, a HTTPS request is made to MM server, transformed to HTTP by the reverse proxy.
3. The MM Server decodes the payload, extract the [integration URL](https://github.com/mattermost/mattermost-server/blob/290d000ad226fb70856f1ec9f04be14a9eafac7f/api4/integration_action.go#L93) and execute a POST request with it.
4. The integration request, which is HTTPS due to SiteURL, fails because of the unconfigured CA.

Not sure how to tackle that :thinking: A spoiler plugin setting to allow to disable https (false by default)?

**Comment by walterl** [comment]
I'm not familiar with the MM's code or how its plugin system works, but your description fits the symptoms.

> A spoiler plugin setting to allow to disable https (false by default)?

That may not work in setups such as mine: any request MM makes to my public host name (`SiteURL`) will go out to the host machine (since the Docker container isn't aware of the reverse proxy) and hit the reverse proxy again. But all unencrypted HTTP traffic is redirected to HTTPS, so the "disable https" effect is neutralised.

How about a plugin setting to override the base integration URL, which defaults to `SiteURL` if empty? That way I can set it to something like `http://localhost` and all will be fine.

Fundamentally it seems like the generated integration URL is "incorrect". Is it MM or the plugin that generates those? If it's MM, then perhaps I should take this issue there.

> Edit: or is it possible to configure Nginx to rewrite the URL in the JSON request to replace the siteURL by the actuel inside-Docker URL?

The failing client request's payload is just `{"selected_option":""}` and I don't see any URL in the rest of the request inputs, so I don't think that would work.

Thanks for your engagement, @moussetc :)

**Comment by moussetc** [comment]
Regarding the integration URL not being visible in the request that is
made when clicking, either it's stocked in the MM server and retrieved
based on the action ID, either it's encoded somewhere in the request.
Either way, it doesn't seem exploitable by the reverse proxy. 

It seems the plugin setting for the base URL to use for the integration
URL is the way to go. 

However, I'm troubled by the fact that this issue should affect all
plugins with integration URLs with this kind of reverse proxied setup.
So before adding the setting, I might take the time to ask the MM dev
team if I'm missing something, an existing config property that I might
use, or if this could be a feature request for the plugin system in the
future. 

Le 24/07/2019 16:39, Walter Leibbrandt a écrit :

> I'm not familiar with the MM's code or how its plugin system works, but your description fits the symptoms.
> 
>> A spoiler plugin setting to allow to disable https (false by default)?
> 
> That may not work in setups such as mine: any request MM makes to my public host name (SiteURL) will go out to the host machine (since the Docker container isn't aware of the reverse proxy) and hit the reverse proxy again. But all unencrypted HTTP traffic is redirected to HTTPS, so the "disable https" effect is neutralised. 
> 
> How about a plugin setting to override the base integration URL, which defaults to SiteURL if empty? That way I can set it to something like http://localhost and all will be fine. 
> 
> Fundamentally it seems like the generated integration URL is "incorrect". Is it MM or the plugin that generates those? If it's MM, then perhaps I should take this issue there.
> 
>> Edit: or is it possible to configure Nginx to rewrite the URL in the JSON request to replace the siteURL by the actuel inside-Docker URL?
> 
> The failing client request's payload is just {"selected_option":""} and I don't see any URL in the rest of the request inputs, so I don't think that would work. 
> 
> Thanks for your engagement, @moussetc [1] :) 
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [2], or mute the thread [3].
 

Links:
------
[1] https://github.com/moussetc
[2]
https://github.com/moussetc/mattermost-plugin-spoiler/issues/4?email_source=notifications&amp;email_token=ACDMZPKW65HXRSEA5MBWJSTQBBSR5A5CNFSM4HFBCV7KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD2WRQ2Q#issuecomment-514660458
[3]

**Comment by walterl** [comment]
> However, I'm troubled by the fact that this issue should affect all
plugins with integration URLs with this kind of reverse proxied setup.
So before adding the setting, I might take the time to ask the MM dev
team if I'm missing something, an existing config property that I might
use, or if this could be a feature request for the plugin system in the
future.

Agreed and thanks again.

**Comment by moussetc** [comment]
Locking this issue because "400 bad request" is a generic error and it's starting to be a catch-all issue. If you, dear reader, have this error, and reading the suggestions in this issue has not helped you, please open a new issue and remember to include the server logs.
